### ISSUE TITLE
After rollup 2.0 update the plugin throws error

### ISSUE THREAD

**Issue by hmt** [sveltejs/rollup-plugin-svelte#98]
I'm a bit at a loss since I don't know how to track this error. So posting an issue here:

```
npm run dev

> schild.report@2.2.0 dev /me/schild.report
> rollup -c && run-p dev:*


src/schild_worker.js, src/repo_worker.js, src/rollup_worker.js, src/preload.js, src/main.js, src/index.js → build...
[!] (plugin svelte) Error: Package subpath './package.json' is not defined by "exports" in /me/schild.report/node_modules/rollup/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /me/schild.report/node_modules/rollup/package.json
    at applyExports (internal/modules/cjs/loader.js:524:9)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.requireRelative.resolve (/me/schild.report/node_modules/require-relative/index.js:30:17)
    at tryResolve (/me/schild.report/node_modules/rollup-plugin-svelte/index.js:50:19)
    at Object.resolveId (/me/schild.report/node_modules/rollup-plugin-svelte/index.js:177:21)
    at /me/schild.report/node_modules/rollup/dist/shared/rollup.js:17441:25
```

This refers to this repo here: https://github.com/schild-report/schild.report

Thank you

**Comment by hmt** [comment]
I added rollup as an external to my rollup.conf and it now works without patching.
